version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    volumes:
      - ./data:/app/data
    depends_on:
      - qdrant
    networks:
      - matrix-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - matrix-network
    restart: unless-stopped

networks:
  matrix-network:
    driver: bridge

volumes:
  qdrant_storage: